# Generated by Django 5.2.1 on 2025-05-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_review_booking_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a representative image for this gig', null=True, upload_to='gig_images/'),
        ),
    ]
